### ISSUE TITLE
Makefile to compile in other OSs 

### ISSUE THREAD

**Issue by rmorros** [yx87cn/MISRE#1]
I have read the paper and the method looks very promising. I would like to try it but I do not use Windows OS. Could you provide a Makefile so that I can compile it in Linux?
Thanks

**Comment by MISRE** [comment]
Hi Josep,
Unfortunately I don't know how exactly to do it. I am not a computer/software major student, but if you know what I can do to generate it out of visual studio, plz tell me.
Xiang
    	
    	

    	
    
  




On Mon, Jun 1, 2020 at 6:56 PM +0800, "Josep Ramon Morros" <notifications@github.com> wrote:















I have read the paper and the method looks very promising. I would like to try it but I do not use Windows OS. Could you provide a Makefile so that I can compile it in Linux?

Thanks

**Comment by rmorros** [comment]
I managed to create a Makefile to compile in Linux/macOS. I'm by no means an expert in this but it works. I made also some small changes to the code to allow the compilation on these OSs. I tested the 'line' model on Linux and in macOS and it works. I did not check extensively the rest of the models but they should be OK as the changes are the same.
 I will create a pull request in GitHub so that you can check the changes and, if you wish, incorporate them in your repository. Before accepting my changes, you should check that they do not produce errors when compiling in Windows. Sorry, I can not test on windows.

By the way, the code for the 'plane' and 'sphere' models are not in the sources folder. Could you upload them to the repository? I do not care much for sphere, but I sure do for the plane model.
Best regards

**Comment by MISRE** [comment]
I uploaded the 3D plane and sphere under the source folder. You could try if it works, and also do me a favor if you have some time to modify it for linux and macOS. 

I really don't know most senior programming techniques. I thank you sincerely for what you contributed to the project.

**Comment by rmorros** [comment]
OK, it is done. The code should work now on python3 and modern versions of OpenCV. I opened another pull request.

Before accepting the changes, remember to test my changes on windows so that I did not introduce windows compilation errors.

I have several questions about how to use the code. 
1. I'm interested in obtaining the parameters of the planes in the scene. This is not described in your example. By looking at the examples in line.py and ellipse.py I tried adding :
       # Plane equation coeffs:
	a, b, c, d = result[structure_count].StructureTLS[: 4]
in planes.py. I assumed that these are the coefficients of the plane ax+by+cz+d=0. Am I right? I created a plot of the planes and it seems to work, but I'm not completely sure.

2. maxDisplayStructure. I Assumed that this parameter is what you refer as iterations in the paper. Am I right?
"Each structure corresponds to an iteration with n ≤ nT points, where nT is the total number of data points.". And, what happens if maxDisplayStructure is larger than the number of structures in the data?

2. In the python code, there is another parameter 'iteration', that is 1 in the plane example, 3 in the line example and infinity in homography and fundamental matrix examples. How do the number of iterations affect the results? And, why is it set to infinity, in homography/fundMat?  

3.  How do you set the parameter 'trial' and how does it affect the results? Does it correspond to the parameter M in the paper?
"The largest Mahalanobis distances ˜di, i = 1, . . . , n, are used in each of the M elemental subset trials"

Maybe you could add some info on the README.md of your repository about how to obtain the parameters for the different models. This should make the code much more usable and your paper more citable :-)

**Comment by MISRE** [comment]
1. The parameters are obtained the way as you did. The parameter is obtained directly by computing the total least squares of the carriers related to the "chosen" inliers. In my opinion, the inlier points are the major concern here, because the parameters are not always computed this way (by TLS) due to the non-linearity. 

2.The "maxDisplayStructure" in Python code is ONLY for display limit. The algorithm in C++ will find as many structures as possible. But in Python I only read the first "maxDisplayStructure". So it could find 10 structures after C++, while we at most show 6 in the paper to apply different color. You should still be able to get the rest from result[structure_count] where structure_count could be 7, 8...(If you do know these structures exists, otherwise I guess there's a stack overflow error)

3.That iteration simply rerun the test again. Each rerun will generate the input data randomly. This is just to show that datapoint could change each time, and will affect the randomly generated sequences. You will eventually see some unstable/incorrect result if you keep trying new dataset. In real images, since the data don't change, the rerun will only generate the 2000/1000 sequences randomly. Sometime you could still see the unstable/incorrect result, this is the limitation of the randomness. In OpenCV, the RANSAC they implemented is not actually random, each time they run the same seed, that is why every time the result looks the same. Therefore, I purposely put 3 iterations in the python code, then the user may see the data change each time, and maybe will see an incorrect result.

4.The trial is the M. The amount of total sampling. "The largest Mahalanobis distances ˜di, i = 1, . . . , n, are used in each of the M elemental subset trials", you can refer to the homography example, where there exists 2 distances for each point-pair. That means 1 input can have 2 distances to the structure. You can also think about a 3D line in the 3D space, because it is an intersection of 2 planes. Then, to judge if a single point is on this line, you could measure if the point is close to both of these planes, that gives 2 distances, one for a plane. In those cases, we simply pick the largest distance.

**Comment by rmorros** [comment]
Many thanks for the answer!
